dist: trusty
install:
- travis_retry sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442
- travis_retry echo 'deb https://download.fpcomplete.com/ubuntu trusty main' | sudo tee /etc/apt/sources.list.d/fpco.list
- travis_retry sudo apt-get update -y
- travis_retry sudo apt-get install stack -y
script:
- stack setup
- stack build
- stack test
