language: haskell

env:
- CABALVER=1.22 GHCVER=7.10.2

before_install:
- travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
- travis_retry cabal update
- cabal install --only-dependencies --enable-tests

script:
- cabal configure
- cabal build
- cabal test
